//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data integrity verified..
        /// </summary>
        internal static string HashCheckEnd {
            get {
                return ResourceManager.GetString("HashCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data integrity check failed..
        /// </summary>
        internal static string HashCheckFailed {
            get {
                return ResourceManager.GetString("HashCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verifying data integrity....
        /// </summary>
        internal static string HashCheckStart {
            get {
                return ResourceManager.GetString("HashCheckStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updater is already running..
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Game is running. Please close the game and try again..
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Final data integrity verified..
        /// </summary>
        internal static string MetaChainCheckEnd {
            get {
                return ResourceManager.GetString("MetaChainCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Final data integrity check failed..
        /// </summary>
        internal static string MetaChainCheckFailed {
            get {
                return ResourceManager.GetString("MetaChainCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verifying final data integrity....
        /// </summary>
        internal static string MetaChainCheckStart {
            get {
                return ResourceManager.GetString("MetaChainCheckStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Downloading data....
        /// </summary>
        internal static string ProgressMessage1 {
            get {
                return ResourceManager.GetString("ProgressMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Downloading ({0}/{1}).
        /// </summary>
        internal static string ProgressMessage2 {
            get {
                return ResourceManager.GetString("ProgressMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download failed. Please try again..
        /// </summary>
        internal static string ProgressMessage3 {
            get {
                return ResourceManager.GetString("ProgressMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extracting data....
        /// </summary>
        internal static string ProgressMessage4 {
            get {
                return ResourceManager.GetString("ProgressMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extraction failed. Please try again..
        /// </summary>
        internal static string ProgressMessage5 {
            get {
                return ResourceManager.GetString("ProgressMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updating data....
        /// </summary>
        internal static string ProgressMessage6 {
            get {
                return ResourceManager.GetString("ProgressMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Update completed..
        /// </summary>
        internal static string ProgressMessage7 {
            get {
                return ResourceManager.GetString("ProgressMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restoring data files....
        /// </summary>
        internal static string ProgressMessage8 {
            get {
                return ResourceManager.GetString("ProgressMessage8", resourceCulture);
            }
        }
    }
}
