<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Copyright>Copyright (c) 2025 Shaiya Duff Inc.</Copyright>
    <Title>Shaiya Duff Updater</Title>
    <Company>shaiya.duff</Company>
    <Product>Shaiya Duff Updater</Product>
    <RepositoryUrl>https://github.com/K3rn3l-P/shaiya-updater</RepositoryUrl>
    <Authors>$(AssemblyName)</Authors>
    <Description></Description>
    <RepositoryType>git</RepositoryType>
    <ApplicationIcon>Resources\Icon\Icon3.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyVersion>3.8.1.4</AssemblyVersion>
    <FileVersion>3.8.1.4</FileVersion>
    <Platforms>x86;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Bitmap\Bitmap167.bmp" />
    <None Remove="Resources\Bitmap\Bitmap168.bmp" />
    <None Remove="Resources\Bitmap\Bitmap169.bmp" />
    <None Remove="Resources\Bitmap\Bitmap170.bmp" />
    <None Remove="Resources\Bitmap\Bitmap185.bmp" />
    <None Remove="Resources\Bitmap\Bitmap187.bmp" />
    <None Remove="Resources\Bitmap\Bitmap188.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icon\Icon3.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Bitmap\Bitmap167.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap168.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap169.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap170.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap185.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap187.bmp" />
    <EmbeddedResource Include="Resources\Bitmap\Bitmap188.bmp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Updater.Interop\Updater.Interop.vcxproj">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources\strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
